# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('post_id', models.IntegerField(default=0)),
                ('count_like', models.IntegerField(default=0)),
            ],
        ),
    ]
